mashup_workshop/examples/tropo/applications/openvoice/config/routes.rb
Openvoice::Application.routes.draw do

  root :to => "user_sessions#new"

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match 'phone_numbers/get_user' => 'phone_numbers#locate_user'
  match 'voicemails/set_transcription' => 'voicemails#set_transcription'
  match 'voicemails/recording' => 'voicemails#recording'
  match 'users/register_phone' => 'users#register_phone'
  match 'logout' => 'user_sessions#destroy'
  match 'incoming_calls/user_menu' => 'incoming_calls#user_menu'
  match 'communications/index' => 'communications#index'
  match 'communications/handle_incoming_call' => 'communications#handle_incoming_call'
  match 'communications/call_screen' => 'communications#call_screen'
  match 'contacts/set_name_recording' => 'contacts#set_name_recording'

  resource :user_session
  resource :account, :controller => "users"
  resources :users do
    member do
      put :suspend
      put :unsuspend
      delete :purge
    end    
    resources :phone_numbers
    resources :voicemails
    resources :messagings
    resources :incoming_calls
    resources :outgoing_calls
    resources :contacts
    resources :profiles
    resources :fs_profiles
  end

end

mashup_workshop/examples/tropo/applications/openvoice/app/models/voicemail.rb
class Voicemail < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :user

  def created_at
    unless self.read_attribute(:created_at).nil?
      self.read_attribute(:created_at).strftime("%a, %b %d")
    end
  end

end

mashup_workshop/examples/tropo/applications/openvoice/app/controllers/voicemails_controller.rb
class VoicemailsController < ApplicationController
  before_filter :require_user, :only => [:index, :show, :new, :edit, :update, :destroy]
  
  def index
    @voicemails = current_user.voicemails.reverse
    @voicemails = @voicemails.paginate(:page => params[:page],:per_page => 15)
    
    respond_to do |format|
      format.html
      format.xml  { render :xml => @voicemails }
      format.json  { render :json => @voicemails }
    end
  end

  def show
    @voicemail = Voicemail.find(params[:id])

    respond_to do |format|
      format.html
      format.xml  { render :xml => @voicemail }
    end
  end

  def new
    @voicemail = Voicemail.new

    respond_to do |format|
      format.html
      format.xml  { render :xml => @voicemail }
    end
  end

  def create
    AWS::S3::Base.establish_connection!(
            :access_key_id     => 'AKIAJL7N4ODM3NMNTFCA',
            :secret_access_key => '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'
    )

    original_filename = params[:filename].original_filename

    AWS::S3::S3Object.store(original_filename,
                            params[:filename],
                            'voicemails-dev.tropovoice.com',
                            :access => :public_read)

    path = 'http://voicemails-dev.tropovoice.com' + '.s3.amazonaws.com/' + original_filename

    # TODO locate user via caller_id
    @voicemail = Voicemail.new(:filename => path,
                               :user_id => params[:user_id],
                               :from => params[:caller_id],
                               :text => "",
                               :transcription_id => params[:transcription_id])
    if @voicemail.save
      flash[:notice] = 'Voicemail was successfully created.'
    end
                                                    
    head 200
  end

  def update
    @voicemail = Voicemail.find(params[:id])

    respond_to do |format|
      if @voicemail.update_attributes(params[:voicemail])
        flash[:notice] = 'Voicemail was successfully updated.'
        format.html { redirect_to(@voicemail) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @voicemail.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @voicemail = Voicemail.find(params[:id])
    @voicemail.destroy

    respond_to do |format|
      format.html { redirect_to(user_voicemails_url) }
      format.xml  { head :ok }
    end
  end

  def set_transcription
    # let the ugliness begin until tropo changes the mal-formed return of transcription results
#    result_to_parse = params["<?xml version"]
#    transcription_id = %r{(.*<identifier>)(.*)(</identifier>.*)}.match(result_to_parse)[2]
#    transcription = %r{(.*<transcription>)(.*)(</transcription>.*)}.match(result_to_parse)[2]
    params.each do |k, v|
      if v == nil
        # this json parse should not be necessary, remove once tropo fix the parameter bug
        json = JSON.parse(k)
        transcription = json["result"]["transcription"]
        transcription_id = json["result"]["identifier"]
        voicemail = Voicemail.find_by_transcription_id(transcription_id)
        voicemail.update_attribute("text", transcription)
        head 200
      end
    end
  end

  def recording
    user_id = params[:user_id]
    user_name = User.find(user_id).name
    transcription_id = params[:transcription_id]
    caller_id = params[:caller_id]
    tropo = Tropo::Generator.new do
      record(:say => [:value => "you have reached #{user_name}\'s voicemail.  Please speak after the beep."],
             :beep => true,
             :maxTime => 30,
             :format => "audio/wav",
             :name => "voicemail",
             :choices => { :terminator => "#" },
             :url => SERVER_URL + "/voicemails/create?caller_id=#{CGI::escape(caller_id)}&transcription_id=" + transcription_id + "&user_id=" + user_id,
             :transcription => {
                     :id => transcription_id,
                     :url => SERVER_URL + "/voicemails/set_transcription"
             })
    end

    render :json => tropo.response
  end

end

mashup_workshop/examples/tropo/applications/openvoice/app/views/voicemails/edit.html.erb
<h1>Editing voicemail</h1>

<% form_for(@voicemail) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :from %><br />
    <%= f.text_field :from %>
  </p>
  <p>
    <%= f.label :to %><br />
    <%= f.text_field :to %>
  </p>
  <p>
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </p>
  <p>
    <%= f.label :uri %><br />
    <%= f.text_field :uri %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @voicemail %> |
<%= link_to 'Back', voicemails_path %>

mashup_workshop/examples/tropo/applications/openvoice/app/views/voicemails/index.html.erb
<h2>Voicemails</h2>

<table>
  <tr class="header">
    <th>From</th>
    <th>Text</th>
    <th>Play</th>
    <th>Time</th>
    <th />
    <th />
  </tr>

<% @voicemails.each do |voicemail| %>
  <tr>
    <td><%=h voicemail.from %></td>
    <td><%=h voicemail.text %></td>
    <td><embed src=<%= voicemail.filename%> height=15 width=144 controls=smallconsole volume=50 autostart=false></td>
    <td><%=h voicemail.created_at %></td>
    <td class="narrow"><%= link_to 'Show', user_voicemail_path(current_user, voicemail) %></td>
    <td class="narrow"><%= link_to 'Destroy', user_voicemail_path(current_user, voicemail), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
<%= will_paginate @voicemails %>
<br />

mashup_workshop/examples/tropo/applications/openvoice/app/views/voicemails/new.html.erb
<h1>New voicemail</h1>

<% form_for(@voicemail) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :from %><br />
    <%= f.text_field :from %>
  </p>
  <p>
    <%= f.label :to %><br />
    <%= f.text_field :to %>
  </p>
  <p>
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </p>
  <p>
    <%= f.label :uri %><br />
    <%= f.text_field :uri %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', voicemails_path %>

mashup_workshop/examples/tropo/applications/openvoice/app/views/voicemails/show.html.erb
<p>
  <b>From:</b>
  <%=h @voicemail.from %>
</p>

<p>
  <b>To:</b>
  <%=h @voicemail.to %>
</p>

<p>
  <b>Text:</b>
  <%=h @voicemail.text %>
</p>

<p>
  <b>Uri:</b>
  <%=h @voicemail.filename %>
</p>

<%= link_to 'Back', user_voicemails_path(current_user) %>