mashup_workshop/examples/tropo/applications/openvoice/config/routes.rb
Openvoice::Application.routes.draw do

  root :to => "user_sessions#new"

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match 'phone_numbers/get_user' => 'phone_numbers#locate_user'
  match 'voicemails/set_transcription' => 'voicemails#set_transcription'
  match 'voicemails/recording' => 'voicemails#recording'
  match 'users/register_phone' => 'users#register_phone'
  match 'logout' => 'user_sessions#destroy'
  match 'incoming_calls/user_menu' => 'incoming_calls#user_menu'
  match 'communications/index' => 'communications#index'
  match 'communications/handle_incoming_call' => 'communications#handle_incoming_call'
  match 'communications/call_screen' => 'communications#call_screen'
  match 'contacts/set_name_recording' => 'contacts#set_name_recording'

  resource :user_session
  resource :account, :controller => "users"
  resources :users do
    member do
      put :suspend
      put :unsuspend
      delete :purge
    end    
    resources :phone_numbers
    resources :voicemails
    resources :messagings
    resources :incoming_calls
    resources :outgoing_calls
    resources :contacts
    resources :profiles
    resources :fs_profiles
  end

end

mashup_workshop/examples/tropo/applications/openvoice/app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user

  before_create :sanitize_number

  def sanitize_number
    # TODO only sanitize PSTN numbers
    # self.number.gsub!(/\D/, "")
  end

  def record_name(session_id, call_id)
    user_id = user.id
    caller_id = CGI::escape(number)
    contact_id = id
    name_recording = self.name_recording
#    signal_url = "signal_peer?event=disconnect&call_id=#{call_id}&session_id=#{session_id}"
    tropo = Tropo::Generator.new do
#      on(:event => 'incomplete', :next => signal_url)
#      on(:event => 'disconnect', :next => signal_url)
      on(:event => 'continue', :next => "/communications/handle_incoming_call?user_id=#{user_id}&caller_id=#{caller_id}&session_id=#{session_id}&call_id=#{call_id}")
      unless name_recording
        record({ :beep => true,
                 :attempts => 2,
                 :name => 'record-name',
                 :url => "#{SERVER_URL}/contacts/set_name_recording?contact_id=#{contact_id}",
                 :format => "audio/mp3",
                 :terminator => "#" }) do
          say "Before being connected please record your name, press pound when you are done"
        end
      end
    end

    tropo.response
  end

  # uploads the recorded name to storage and set the name_recording attribute of contact with the url
  def set_name_recording(file_name)
    AWS::S3::Base.establish_connection!(
            :access_key_id     => 'AKIAJL7N4ODM3NMNTFCA',
            :secret_access_key => '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'
    )

    original_filename = file_name.original_filename

    AWS::S3::S3Object.store(original_filename,
                            file_name,
                            'voicemails-dev.tropovoice.com',
                            :access => :public_read)

    path = 'http://voicemails-dev.tropovoice.com' + '.s3.amazonaws.com/' + original_filename
    update_attribute(:name_recording, path)
  end

  def hangup
    Tropo::Generator.new{ hangup }.to_json
  end

#  def signal_peer
#    tropo_url = "http://api.tropo.com/1.0/sessions/#{session_id}/calls/#{call_id}/events?action=create&name=#{event}"
#    open(tropo_url)
#    render head 204
#  end

end

mashup_workshop/examples/tropo/applications/openvoice/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_filter :require_user, :only => [:index, :show, :new, :edit, :create, :update, :destroy]

  def index
    @contacts = current_user.contacts
    @contacts = @contacts.paginate(:page => params[:page], :per_page => 15)

    respond_to do |format|
      format.html
      format.xml { render :xml => @contacts }
    end
  end

  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render :xml => @contact }
    end
  end

  def new
    @contact = Contact.new

    respond_to do |format|
      format.html
      format.xml { render :xml => @contact }
    end
  end

  def edit
    @user = current_user
    @contact = Contact.find(params[:id])
  end

  def create
    @contact = Contact.new(params[:contact].merge(:user_id => params[:user_id]))

    respond_to do |format|
      if @contact.save
        flash[:notice] = 'Contact was successfully created.'
        format.html { redirect_to(user_contacts_path(current_user)) }
        format.xml { render :xml => @contact, :status => :created, :location => @contact }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        flash[:notice] = 'Contact was successfully updated.'
        format.html { redirect_to(user_contacts_path) }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to(user_contacts_path) }
      format.xml { head :ok }
    end
  end

  def set_name_recording
    contact = Contact.find(params[:contact_id])
    # TODO handle contact not found
    contact.set_name_recording(params[:filename])
    render :content_type => 'text/plan', :text => "STORED"
  end
  
end

mashup_workshop/examples/tropo/applications/openvoice/app/helpers/contacts_helper.rb
module ContactsHelper
end

mashup_workshop/examples/tropo/applications/openvoice/app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<% form_for([@user, @contact]) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </p>
  <p>
    <%= f.label :im %><br />
    <%= f.text_field :im %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', user_contact_path(current_user, @contact) %> |
<%= link_to 'Back', user_contacts_path(current_user) %>

mashup_workshop/examples/tropo/applications/openvoice/app/views/contacts/index.html.erb
<h2>Contacts</h2>

<%= link_to 'New contact', new_user_contact_path(current_user) %>
<br /><br />
<table>
  <tr class="header">
    <th>Name</th>
    <th>Number</th>
    <th>IM</th>
    <th />
    <th />
    <th />
    <th />
    <th />
  </tr>

<% @contacts.each do |contact| %>
  <tr>
    <td><%=h contact.name %></td>
    <td><%=h contact.number %></td>
    <td><%=h contact.im %></td>
    <td class="narrow"><%= link_to 'Call', new_user_outgoing_call_path(current_user, { :callee_number => contact.number }) %></td>
    <td class="narrow"><%= link_to 'SMS', new_user_messaging_path(current_user, { :to => contact.number }) %></td>
    <td class="narrow"><%= link_to 'Show', user_contact_path(current_user, contact) %></td>
    <td class="narrow"><%= link_to 'Edit', edit_user_contact_path(current_user, contact) %></td>
    <td class="narrow"><%= link_to 'Destroy', user_contact_path(current_user, contact), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>


<br />
<%= will_paginate @contacts %>
<br />

mashup_workshop/examples/tropo/applications/openvoice/app/views/contacts/new.html.erb
    <h1>New contact</h1>

<% form_for([:user, @contact]) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </p>
  <p>
    <%= f.label :im %><br />
    <%= f.text_field :im %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', user_contacts_path(current_user) %>

mashup_workshop/examples/tropo/applications/openvoice/app/views/contacts/show.html.erb
<p>
  <b>Name:</b>
  <%=h @contact.name %>
</p>

<p>
  <b>Number:</b>
  <%=h @contact.number %>
</p>

<p>
  <b>IM:</b>
  <%=h @contact.im %>
</p>

<p>
  <b>Name recording:</b>
  <embed src=<%= @contact.name_recording%> height=15 width=144 controls=smallconsole volume=50 autostart=false>
</p>

<%= link_to 'Edit', edit_user_contact_path(current_user, @contact) %> |
<%= link_to 'Back', user_contacts_path(current_user) %>