mashup_workshop/examples/tropo/applications/openvoice/config/routes.rb
Openvoice::Application.routes.draw do

  root :to => "user_sessions#new"

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match 'phone_numbers/get_user' => 'phone_numbers#locate_user'
  match 'voicemails/set_transcription' => 'voicemails#set_transcription'
  match 'voicemails/recording' => 'voicemails#recording'
  match 'users/register_phone' => 'users#register_phone'
  match 'logout' => 'user_sessions#destroy'
  match 'incoming_calls/user_menu' => 'incoming_calls#user_menu'
  match 'communications/index' => 'communications#index'
  match 'communications/handle_incoming_call' => 'communications#handle_incoming_call'
  match 'communications/call_screen' => 'communications#call_screen'
  match 'contacts/set_name_recording' => 'contacts#set_name_recording'

  resource :user_session
  resource :account, :controller => "users"
  resources :users do
    member do
      put :suspend
      put :unsuspend
      delete :purge
    end    
    resources :phone_numbers
    resources :voicemails
    resources :messagings
    resources :incoming_calls
    resources :outgoing_calls
    resources :contacts
    resources :profiles
    resources :fs_profiles
  end

end

mashup_workshop/examples/tropo/applications/openvoice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta charset="utf-8">

<head>
  <title>OpenVoice - <%= controller.controller_name %>:<%= controller.action_name %></title>
  <%= stylesheet_link_tag "openvoice" %>
</head>

<body>
<div class="container">
  <div class="header">
    <%= image_tag("ov_logo.png", :size => "35x35") %>
    <h1 class="header">OpenVoice</h1>
  </div>

  <div>
    <div>
      <% unless current_user.nil? %>
          <%= link_to_unless_current "inbound calls", user_incoming_calls_path(current_user), :class => 'special' %> |
          <%= link_to_unless_current "outbound calls", user_outgoing_calls_path(current_user), :class => 'special' %> |
          <%= link_to_unless_current "messages", user_messagings_path(current_user), :class => 'special' %> |
          <%= link_to_unless_current "voicemails", user_voicemails_path(current_user), :class => 'special' %> |
          <%= link_to_unless_current "addressbook", user_contacts_path(current_user), :class => 'special' %> |
          <%= link_to_unless_current "phone numbers", user_phone_numbers_path(current_user), :class => 'special' %> |
          <%= link_to_unless_current "profile", user_profiles_path(current_user), :class => 'special' %> |
          <%= link_to_unless_current "fs_profile", user_fs_profiles_path(current_user), :class => 'special' %> |
          <%= link_to_unless_current "account", account_path, :class => 'special' %> |
          <a class="special" href="/logout">logout</a>
      <% end %>
    </div>

    <% if flash[:error]  %>
    <div id="flash_error">
        <%= flash[:error] %>
    </div>
    <% end %>

    <% if flash[:notice]  %>
    <div id="flash_notice">
        <p><%= flash[:notice] %></p>
    </div>
    <% end %>
    
    <div>
      <%= yield %>
    </div>
  </div>

  <div class="footer">Copyright 2010, Zhao Lu <a href="http://myopenvoice.org">OpenVoice</a>.</div>
</div>

</body>