mashup_workshop/examples/tropo/applications/openvoice/config/routes.rb
Openvoice::Application.routes.draw do

  root :to => "user_sessions#new"

  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  match 'phone_numbers/get_user' => 'phone_numbers#locate_user'
  match 'voicemails/set_transcription' => 'voicemails#set_transcription'
  match 'voicemails/recording' => 'voicemails#recording'
  match 'users/register_phone' => 'users#register_phone'
  match 'logout' => 'user_sessions#destroy'
  match 'incoming_calls/user_menu' => 'incoming_calls#user_menu'
  match 'communications/index' => 'communications#index'
  match 'communications/handle_incoming_call' => 'communications#handle_incoming_call'
  match 'communications/call_screen' => 'communications#call_screen'
  match 'contacts/set_name_recording' => 'contacts#set_name_recording'

  resource :user_session
  resource :account, :controller => "users"
  resources :users do
    member do
      put :suspend
      put :unsuspend
      delete :purge
    end    
    resources :phone_numbers
    resources :voicemails
    resources :messagings
    resources :incoming_calls
    resources :outgoing_calls
    resources :contacts
    resources :profiles
    resources :fs_profiles
  end

end

mashup_workshop/examples/tropo/applications/openvoice/app/models/fs_profile.rb
class FsProfile < ActiveRecord::Base
  belongs_to :user
end

mashup_workshop/examples/tropo/applications/openvoice/app/controllers/fs_profiles_controller.rb
class FsProfilesController < ApplicationController

  before_filter :require_user, :only => [:index, :show, :new, :edit, :create, :update, :destroy]

  def index
    @user = User.find(params[:user_id])
    @profiles = @user.fs_profiles

    respond_to do |format|
      format.html
      format.xml { render :xml => @profiles }
    end
  end

  def show
    @profile = FsProfile.find(params[:id])

    respond_to do |format|
      format.html
      format.xml { render :xml => @profile }
    end
  end

  def new
    @profile = FsProfile.new

    respond_to do |format|
      format.html
      format.xml { render :xml => @profile }
    end
  end

  def edit
    @user = current_user
    @profile = FsProfile.find(params[:id])
  end

  def create
    @profile = FsProfile.new(params[:fs_profile].merge(:user_id => params[:user_id]))

    respond_to do |format|
      if @profile.save
        flash[:notice] = 'FsProfile was successfully created.'
        format.html { redirect_to(user_fs_profiles_path(current_user)) }
        format.xml { render :xml => @profile, :status => :created, :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @profile = FsProfile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:fs_profile])
        flash[:notice] = 'FreeSwitch Profile was successfully updated.'
        format.html { redirect_to(user_fs_profiles_path(current_user)) }
        format.xml { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @profile = FsProfile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to(user_fs_profiles_url(current_user)) }
      format.xml { head :ok }
    end
  end
end

mashup_workshop/examples/tropo/applications/openvoice/app/helpers/fs_profiles_helper.rb
module FsProfilesHelper
end

mashup_workshop/examples/tropo/applications/openvoice/app/views/fs_profiles/edit.html.erb
<h1>Editing FreeSwitch profile</h1>
<% form_for([@user, @profile]) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :sip_address %><br />
    <%= f.text_field :sip_address %>
  </p>

  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', user_fs_profiles_path(current_user, @profile) %> |
<%= link_to 'Back', user_fs_profiles_path(current_user) %>

mashup_workshop/examples/tropo/applications/openvoice/app/views/fs_profiles/index.html.erb
<h2>FreeSwitch Profiles</h2>
<%= link_to 'New FS profile', new_user_fs_profile_path(current_user) %>
<br /><br />

<% @profiles.each do |profile| %>
    <b>SIP Address:</b>
    <%= h profile.sip_address %>
    <br/>
    <%= link_to 'Show', user_fs_profile_path(current_user, profile) %>
    <%= link_to 'Edit', edit_user_fs_profile_path(current_user, profile) %>
    <%= link_to 'Destroy', user_fs_profile_path(current_user, profile), :confirm => 'Are you sure?', :method => :delete %>
<% end %>

mashup_workshop/examples/tropo/applications/openvoice/app/views/fs_profiles/new.html.erb
<h1>New FreeSwitch profile</h1>

<% form_for([:user, @profile]) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :sip_address %><br />
    <%= f.text_field :sip_address %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', user_fs_profiles_path(current_user) %>

mashup_workshop/examples/tropo/applications/openvoice/app/views/fs_profiles/show.html.erb
<p>
  <b>SIP Address:</b>
  <%=h @profile.sip_address %>
</p>

<%= link_to 'Edit', edit_user_fs_profile_path(current_user, @profile) %> |
<%= link_to 'Back', user_fs_profiles_path(current_user) %>